name: auth-deploy

on:
  push:
    branches:
      - master
    paths:
      - 'auth/**'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - run: cd auth && docker build -t simkamax777/auth .
      - run: docker login -u $DOCKER_ID -p $DOCKER_PASSWORD
        env:
          DOCKER_ID: $({ secrets.DOCKER_ID})
          DOCKER_PASSWORD: $({ secrets.DOCKER_PASSWORD})
      - run: docker push simkamax777/auth
      - uses: digitalocean/action-doctl@v2
        with:
          token: $({ secrets.DIGITALOCEAN_ACCESS_TOKEN})
      - run: doctl kubernetes cluster kubeconfig save 'name of cluster'
      - run: kubectl rollout restart deployment auth-depl
